server:
  port: 8083
spring:
  application:
    name: gulimall-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.187.214:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: qwe123
  jackson:
    date-format: YYYY-MM-DD HH:MM:SS
  thymeleaf:
    check-template: false
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
  session:
    store-type: redis
    timeout: 30m

    #配置spring 缓存
  cache:
    type: redis
    redis:
      #开启缓存空值 防止缓存穿透
      cache-null-values: true
      #如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      key-prefix: CACHE_
      use-key-prefix: true
      #设置过期时间
      time-to-live: 3600000
mybatis-plus:
  type-aliases-package: com.lxsx.gulimall.product.entity
  mapper-locations: classpath:mapper/**/*.xml
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: auto
gulimall:
  thread:
    core-size: 20
    keep-alicve-time: 10
    max-size: 200


#seata:
#  tx-service-group: gulimall_order_group  #对应seataServer.properties中的service.vgroupMapping.my_test_tx_group 集群分组
#  service:
#    vgroup-mapping:
#      gulimall_order_group: seata-server
#  registry:
#    type: nacos   #注册中心类型：nacos
#    nacos:
#      application: seata-server      # seata-server注册在nacos中的服务名
#      server-addr: 162.14.77.50:8848   # nacos的地址端口
#      group : SEATA_GROUP            # seata-server在nacos的分组
#      namespace: seata4345b4af-fd9f-4a57-836b-705c7ae10c70 # seata-server在nacos的命名空间ID
#      username: nacos                # nacos账号
#      password: nacos                # nacos密码
#  config:
#    type: nacos
#    nacos:
#      server-addr: 162.14.77.50:8848
#      group: SEATA_GROUP
#      namespace: 4345b4af-fd9f-4a57-836b-705c7ae10c70 # seata-server的配置文件的命名空间ID
#      dataId: seataServer.properties       # seata-server在nacos的配置dataId
#      username: nacos
#      password: nacos