#server:
#  port: 8085
#spring:
#  application:
#    name: gulimall-gateway-server
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 162.14.77.50:8848
#    # 网关的配置过滤 断言 和路由
#    gateway:
#      globalcors: # 全局的跨域处理
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"# 允许哪些网站的跨域请求
#            allowedMethods: # 允许的跨域ajax的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
#      routes:
#        - id: admin-route
#          uri: lb://renren-fast
#          predicates:
#            - Path=/api/**
#          filter:
#            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
#        - id: product-route
#          uri: lb://gulimall-product
#          predicates:
#            - Path=/api/**
#          filter:
#            - RewritePath=/api/(?<segment>.*),/$\{segment}



