server:
  port: 10000
spring:
  application:
    name: gulimall-auth
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.77.50:8848
        enabled: true
  jackson:
    date-format: YYYY-MM-DD HH:MM:SS
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: false
  redis:
    host: localhost
    port: 6379
    #配置springSession
  session:
    store-type: redis
    timeout: 30m