server:
  port: 9003
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true

  redis:
    host: localhost
    port: 6379

  session:
    timeout: 30m
    store-type: redis
