server:
  port: 10002
spring:
  application:
    name: gulimall-seckill
  redis:
    port: 6379
    host: localhost
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 162.14.77.50:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
    #    clientIp: localhost       #指定和控制台通信的IP，若不配置，会自动选择一个IP注册


  jackson:
    date-format: YYYY-MM-DD HH:MM:SS
  session:
    store-type: redis

  task:
    execution:
      pool:
        core-size: 20
        max-size: 200
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false
    check-template-location: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
