server:
  port: 9001
spring:
  application:
    name: aliyun-third-api
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.77.50:8848
    alicloud:
      access-key: LTAI5tDpwvtZL5JHNnUmSuTN
      secret-key: aYRnwujwf07OprKmsNrSMQXORRCiUV
      oss:
        endpoint: oss-cn-chengdu.aliyuncs.com
        bucket-name: gulimall-lxsx
      sms:
        host: https://dfsns.market.alicloudapi.com
        appcode: 1ecf90a9186f42bfb6d2a0661e4885cb
        method: POST
        template-id: TPL_0000
        path: /data/send_sms
