server:
  port: 8084
spring:
  application:
    name: gulimall-ware
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_wms?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwe123
  jackson:
    date-format: YYYY-MM-DD HH:MM:SS
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    #broker收到消息后的简单回调开启
    publisher-confirm-type: simple
    #开启息递交队列失败的回调
    publisher-returns: true
    #将消费方ACK机制 修改为手动签收
    listener:
      simple:
        acknowledge-mode: manual
    virtual-host: /

  #Spring session 配置
  session:
    store-type: redis
  cloud:
    alibaba:
      seata:
        tx-service-group: gulimall_order_group




mybatis-plus:
  type-aliases-package: com.lxsx.gulimall.product.entity
  mapper-locations: classpath:mapper/**/*.xml
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: auto
seata:
  # 默认关闭，如需启用spring.datasource.dynami.seata需要同时开启
  enabled: true
  # Seata 应用编号，默认为 ${spring.application.name}
  application-id: ${spring.application.name}
  tx-service-group: gulimall_order_group  #对应seataServer.properties中的service.vgroupMapping.my_test_tx_group 集群分组
  # 关闭自动代理
  enable-auto-data-source-proxy: true
  data-source-proxy-mode: AT

  service:
    vgroup-mapping:
      gulimall_order_group: default
  registry:
    type: nacos   #注册中心类型：nacos
    nacos:
      cluster: default
      application: seata-server      # seata-server注册在nacos中的服务名
      server-addr: 162.14.77.50:8848   # nacos的地址端口
      group : SEATA_GROUP            # seata-server在nacos的分组
      namespace: 4345b4af-fd9f-4a57-836b-705c7ae10c70 # seata-server在nacos的命名空间ID
      username: nacos                # nacos账号
      password: nacos                # nacos密码
  config:
    type: nacos
    nacos:
      server-addr: 162.14.77.50:8848
      group: SEATA_GROUP
      namespace: 4345b4af-fd9f-4a57-836b-705c7ae10c70 # seata-server的配置文件的命名空间ID
      dataId: seataServer.properties       # seata-server在nacos的配置dataId
      username: nacos
      password: nacos
